name=DFRobot_N20SerialMotor
version=1.0.0
author=DFRobot
maintainer=JiaLi <zhixin.liu@dfrobot.com>
sentence=DFR1277 serial N20 motor driver Arduino library.
paragraph=Modbus-RTU based N20 motor control library, supports speed, direction, address/baud configuration and address scan.
category=Device Control
url=https://github.com/DFRobot/DFRobot_N20SerialMotor
architectures=*
depends=DFRobot_RTU
